### ISSUE TITLE
Register the keys in the application in the env file

### ISSUE THREAD

**Issue by Eliyahu-Yishai** [Food-Rescue-Social-Media-Platform/Food-Rescue-social-media-application#135]
So that the keys don't go up to the public github, you have to put them in an env file that doesn't go up to github, like for example type information in firebase.js and the key of the maps, etc.

**Comment by Eliyahu-Yishai** [comment]
fixed

**Comment by mohammadBelbesi** [comment]
there are a lot of keys that i add to env file and git ignore + i delete all the keys from GitHub cache
